name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
    - master
    tags:
    - "v*.*.*"

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: |
          TAG=$(basename ${GITHUB_REF})
          VERSION=${TAG/v/}
          echo "::set-output name=TAG::$TAG"
          echo "::set-output name=VERSION::$VERSION"
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yml
          version: ${{ steps.get_version.outputs.TAG }}
          tag: ${{ steps.get_version.outputs.TAG }}
          prerelease: contains(github.ref, "refs/tags") && contains(github.ref "-rc.")
          publish: contains(github.ref, "refs/tags") && !contains(github.ref "-rc.") 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}